_home/urls.py
from django.urls import path
from _home.views import home_view, login_view, login_done, logout_view

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('login/done', login_done, name='login-done'),
    path('logout/', logout_view, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('_home.urls', namespace='home')),
    path('indicadores/', include('_dashboards.urls', namespace='dashboards')),
    path('ramais/', include('_ramais.urls', namespace='ramais')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

_home/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

_home/views.py
from django.shortcuts import render, redirect
from _home.forms import LoginForm
from django.urls import reverse
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def home_view(request):
    return render(request, 'home/main.html')


def login_view(request):
    form = LoginForm()
    return render(request, 'home/auth/login.html', {
        'form': form,
        'form_action': reverse('home:login-done')
    })


def login_done(request):
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)

    if form.is_valid():
        username = form.cleaned_data.get('username', '')
        password = form.cleaned_data.get('password', '')

        user = authenticate(
            username=username,
            password=password,
        )

        if user is not None:
            login(request, user)
            return redirect(reverse('home:home'))
        else:
            messages.error(request, 'Dados inválidos')
    else:
        messages.error(request, 'Preencha todos os campos')

    return render(request, 'home/auth/login.html', {
        'form': form,
        'form_action': reverse('home:login-done')
    })


def logout_view(request):
    logout(request)
    messages.success(request, 'Você se desconectou com sucesso')
    return redirect('home:login')

_home/templates/home/main.html
{% extends 'global/base_with_sidebar.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block head %}
        <link href="{% static 'home/css/home.css' %}" rel="stylesheet">
{% endblock head %}

{% block menu %}
    <a href="{% url "ramais:home" %}" title="Acessar Lista de Ramais">
        <i class="fas fa-phone"></i>
        <span class="text">Lista de Ramais</span>
    </a>
    <a href="{% url "dashboards:home" %}" title="Acessar Central de Indicadores">
        <i class="fas fa-chart-pie"></i>
        <span class="text">Central de Indicadores</span>
    </a>
    <a href="http://servicos.gruposmi.com.br/front/ticket.php" title="Acessar Central de Chamados">
        <i class="fas fa-headphones"></i>
        <span class="text">Central de Chamados</span>
    </a>
{% endblock menu %}

{% block bottom %}
    <div class="user-menu">
        <a href="#" class="user-toggle" id="user-toggle" title="{{ request.user }}">
            <i class="fas fa-user-tie"></i>
            <span class="text">{{ request.user }}</span>
            <i class="fas fa-chevron-down dropdown-icon"></i>
        </a>
        <div class="user-dropdown" id="user-dropdown">
            {% if request.user.is_staff %}
                <a href="{% url "admin:index" %}" title="Acessar Portal de Controle do Site">
                    <i class="fa-solid fa-screwdriver-wrench"></i>
                    <span>Portal de Administração</span>
                </a>
            {% endif %}
            <a href="{% url "home:logout" %}" title="Fazer Logout">
                <i class="fas fa-sign-out-alt"></i>
                <span>Sair</span>
            </a>
        </div>
    </div>
{% endblock bottom %}

{% block content %}{% endblock content %}

{% block scripts %}
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock scripts %}