_home/urls.py
from django.urls import path
from _home.views import home_view, login_view, login_done, logout_view

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('login/done', login_done, name='login-done'),
    path('logout/', logout_view, name='logout'),
]

_ramais/urls.py
from django.urls import path
from _ramais.views import home_view, ramais_json

app_name = 'ramais'

urlpatterns = [
    path('', home_view, name='home'),
    path('api/', ramais_json, name='ramais_json'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('_home.urls', namespace='home')),
    path('indicadores/', include('_dashboards.urls', namespace='dashboards')),
    path('ramais/', include('_ramais.urls', namespace='ramais')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

_ramais/models.py
from django.db import models


class Ramais(models.Model):
    SETORES = [
        ('Almoxarifado', 'Almoxarifado'),
        ('Comercial', 'Comercial'),
        ('Controle', 'Controle'),
        ('Compras', 'Compras'),
        ('Contabilidade', 'Contabilidade'),
        ('Custos', 'Custos'),
        ('Diretoria', 'Diretoria'),
        ('Engenharia', 'Engenharia'),
        ('Financeiro', 'Financeiro'),
        ('Fiscal', 'Fiscal'),
        ('Gestão de Pessoas', 'Gestão de Pessoas'),
        ('Gestão Industrial', 'Gestão Industrial'),
        ('Industria de Apontamento', 'Industria de Apontamento'),
        ('Industria de Eletrônicos', 'Industria de Eletrônicos'),
        ('Industria de Esferas', 'Industria de Esferas'),
        ('Industria Metalúrgica', 'Industria Metalúrgica'),
        ('Industria de Placas', 'Industria de Placas'),
        ('Industria de Tachas', 'Industria de Tachas'),
        ('Industria de Tintas', 'Industria de Tintas'),
        ('Jurídico', 'Jurídico'),
        ('Licitação', 'Licitação'),
        ('Logística', 'Logística'),
        ('Manutenção', 'Manutenção'),
        ('Marketing', 'Marketing'),
        ('Monitoramentos', 'Monitoramentos'),
        ('Obras', 'Obras'),
        ('Projetos', 'Projetos'),
        ('Qualidade', 'Qualidade'),
        ('Recebimentos', 'Recebimentos'),
        ('Recursos Humanos', 'Recursos Humanos'),
        ('Secretaria', 'Secretaria'),
        ('Segurança do Trabalho', 'Segurança do Trabalho'),
        ('Tecnologia', 'Tecnologia'),
        ('Trânsito', 'Trânsito'),
    ]

    nome = models.CharField(max_length=100, blank=True)
    ramal = models.CharField(max_length=20, blank=True)
    setor = models.CharField(max_length=100, blank=True, choices=SETORES)
    maquina = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return f'{self.nome} - {self.ramal}'

    class Meta:
        ordering = ['nome']
        verbose_name = 'Ramal'
        verbose_name_plural = 'Ramais'

_ramais/views.py
from _ramais.models import Ramais
from django.http import JsonResponse
from django.shortcuts import render


def home_view(request):
    return render(request, 'ramais/main.html', {
        'is_staff': request.user.is_staff
    })


def ramais_json(request):
    dados = list(Ramais.objects.values('nome', 'ramal', 'setor', 'maquina'))
    return JsonResponse(dados, safe=False)

_ramais/templates/ramais/main.html
{% extends 'global/base.html' %}
{% load static %}

{% block title %}Ramais{% endblock title %}

{% block head %}
        <link href="{% static 'ramais/css/main.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
        <div id="content" class="container">
            <div class="header">
                {% if user.is_authenticated %}
                <a href="{% url "home:home" %}">
                    <img src="{% static 'global/images/black_logo.png' %}" alt="Logo SMI" class="logo" id="logo-img" title="Voltar ao Menu Principal"/>
                </a>
                {% else %}
                <a href="{% url "ramais:home" %}">
                    <img src="{% static 'global/images/black_logo.png' %}" alt="Logo SMI" class="logo" id="logo-img" title="Recarregar a Página"/>
                </a>
                {% endif %}
                <div class="header-text">
                    <h1>Lista de Ramais</h1>
                    <div class="search-container">
                        <input type="text" id="search-input" placeholder="Pesquise aqui..." oninput="filtrarRamais()"/>
                    </div>
                </div>
            </div>
            <table id="lista-ramais">
            <thead>
                <tr>
                <th><div class="header-cell">Nome</div></th>
                <th><div class="header-cell">Ramal</div></th>
                <th><div class="header-cell">Setor</div></th>
                {% if request.user.is_staff %}
                <th><div class="header-cell">Máquina</div></th>
                {% endif %}
                </tr>
            </thead>
            <tbody></tbody>
            </table>
            <div id="paginacao" class="paginacao-container"></div>
        </div>
        <script>
            const isStaff = {% if request.user.is_staff %}true{% else %}false{% endif %};
        </script>
        <script src="{% static 'ramais/js/main.js' %}"></script>
{% endblock body %}